name: accordion_widget
description: A customizable and lightweight accordion widget for Flutter.
version: 1.0.0

repository: https://github.com/Nabawy12/accordion_widget
homepage: https://github.com/Nabawy12/accordion_widget
issue_tracker: https://github.com/Nabawy12/accordion_widget/issues


environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_svg: ^2.0.17

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
